### ISSUE TITLE
ytns doesn't work when used on an iPad (layout)

### ISSUE THREAD

**Issue by Macleykun** [jkhsjdhjs/youtube-native-share#2] opened 2024-06-11 11:56 UTC
Refering from this issue: https://github.com/YTLitePlus/YTLitePlus/issues/165
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 17.5.1
- Device model: iPad 9th gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): side store 
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): v19.21.3-4.0

### Describe the bug

The [youtube-native-share](https://github.com/jkhsjdhjs/youtube-native-share) doesn’t work
 See: https://github.com/jkhsjdhjs/youtube-native-share?tab=readme-ov-file#what
If you toggle this tweak on/off it doesn’t change the style sheet.

### Steps to reproduce the issue

1. Navigate in YouTube Plus to interface.
2. In interface toggle Native share sheet ON.
3. Restart the app to be sure.
4. Observe no difference.

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

![IMG_1034](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/4bf76f82-2c7e-4320-9ad2-c5e7bad66604)
![IMG_1033](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/a6cdc854-f65f-4a38-8d3d-6f784ab96383)

![IMG_1035](https://github.com/YTLitePlus/YTLitePlus/assets/26381427/a8fc415b-2c49-4f77-9a52-d4ed7b024a0b)

It seems that when using this tweak on an iPad, it doesn't work as expected and uses the yt default sharesheet.
This can be replicated using ytliteplus (e.g.) and toggeling on the iPad Layout option to force the different layout.

**Comment by jkhsjdhjs** [comment] 2024-06-15 20:47
I just pushed a fix for this. Let me know if you encounter any issues!

**Comment by Macleykun** [comment] 2024-06-15 20:48
Thank you so much for taking the time to look into this!


> I just pushed a fix for this. Let me know if you encounter any issues!

Will do! Have a great weekend :) <3

**Comment by Macleykun** [comment] 2024-06-23 19:21
> RPReplay_Final1719108127.mp4 
> Here’s this video of me trying it on iPad, and it will show a crash 🤔 also this was tested when using the uYouEnhanced tweak.

thanks for testing this out for me!

**Comment by jkhsjdhjs** [comment] 2024-06-24 10:23
Hmm, do you have a stacktracke or something similar that shows where exactly it crashes? I don't have an iPad so I can't test it unfortunately.

**Comment by jkhsjdhjs** [comment] 2024-06-24 22:03
> but would that take forever to find the problem in it?

Not sure, feel free to share it, I'll have a look :D

**Comment by jkhsjdhjs** [comment] 2024-06-25 23:25
Hmm, indeed I couldn't read much out of the ips file, but I suspect it's probably a null pointer deref caused by returning NULL here:
https://github.com/jkhsjdhjs/youtube-native-share/blob/6081d80503dc749688c0bed92c3b6290daa85cba/Tweak.x#L116-L121

Can you try building YouTube without this hook and check if the app still crashes? (the tweak shouldn't work in this case, this is just to determine the cause of the crash)

Also thanks for the hint with the version comparison, might come in handy! I don't need it for this tweak, as `ELMPBShowActionSheetCommand.executeWithCommandContext` just isn't called on pre-17.33.2 YouTube versions, so this tweak won't cause any issues on older versions anyway.

**Comment by jkhsjdhjs** [comment] 2024-07-08 23:05
@arichornloverALT Thanks for testing this and sorry for the late reply - was busy studying for exams. I found a class that I can hook for iPad sharing to work, without returning NULL anywhere, thus not causing any exceptions. It's not as optimal as the iPhone hook, as it is called not just for sharing but also for other events like starting a new video, but the overhead isn't that bad since we return early, so it should be fine. Can you test this?

Also I currently hook both classes on iPad and iPhone, while only one of these is necessary on either platform. Do you know if it's possible to only hook `YTAccountScopedCommandResponderEvent` on iPad and `ELMPBShowActionSheetCommand` only on iPhones? Thanks in advance!

**Comment by jkhsjdhjs** [comment] 2024-07-10 10:40
Alright, take your time 👍

**Comment by jkhsjdhjs** [comment] 2024-07-10 20:17
Hmm, that's odd. But can you confirm that it works on your iPhone using the iPad Layout option of YTLitePlus?

**Comment by jkhsjdhjs** [comment] 2024-07-10 23:41
> Does the sharing functionality work differently when using a different iPad model?

Oof, I really don't hope so.

Can you post the full `lastExceptionBacktrace` line? It seems to be cut off after `[UIPopoverPresentationController presentationTransitionWillBegin]",`, maybe this can help. Other than that I really don't know what could go wrong here, the hook is pretty much error-proof. I never make any assumptions about GPBMessage extensions and explicitely check whether each extension is present. If anything isn't right, I just `return %orig`.

**Comment by Macleykun** [comment] 2024-07-11 06:59
> > Hmm, that's odd. But can you confirm that it works on your iPhone using the iPad Layout option of YTLitePlus?
> 
> I didn’t update YTLitePlus on the phone, it’s been on an old version which I’ll be updating in a bit, but was wondering about the **iPad Layout** implementation. Does the sharing functionality work differently when using a different iPad model? That’s what I am assuming.

perhaps i can test it out on my real iPad? I do need a bit of help with getting the ipa to test it and how i can generate the debug logging if it doesn't work.
Also i really appricate the help and interest of you two to make this tweak work on iPad's aswell!

**Comment by Macleykun** [comment] 2024-07-11 08:14
> Heres this ipa https://github.com/arichornloverALT/uYouEnhanced/releases/download/v19.24.2-3.0.4-(32)/uYouEnhanced_19.24.2-3.0.4.ipa And its the same one I’m using.

downloaded it, if you want to remove the link just in case.
Will test it out asap

**Comment by Macleykun** [comment] 2024-07-11 08:29
test it out just now, but it crashes the moment i tab on the share button.
would it be helpful if i also send my logs from my ipad (tried looking into flex but couldn't find anything right off the bat)

**Comment by jkhsjdhjs** [comment] 2024-07-11 08:46
```
[UIPopoverPresentationController presentationTransitionWillBegin]
```

Hmm, is the way I'm presenting the share dialog maybe not supported on iPads?

@arichornloverALT Can you try building the tweak without the following line?

https://github.com/jkhsjdhjs/youtube-native-share/blob/ba86bc03f4f34624a542a5b66fe85a3ab7e64ef5/Tweak.x#L113

**Comment by jkhsjdhjs** [comment] 2024-07-11 10:24
Very nice, thanks for testing this! Maybe we can find a way to pop up a share menu that works on both platforms. However, I really don't know what's wrong with the way it is currently being done.

**Comment by jkhsjdhjs** [comment] 2024-07-11 10:29
This may be the problem: https://stackoverflow.com/a/25644145

**Comment by jkhsjdhjs** [comment] 2024-07-11 19:45
I think you can keep the Idiom part and just present the share sheet a bit different, the if/else looks fine to me. If the iPad way also works on iPhone, you can also just do the iPad method in both cases, which would remove the need for an if/else.

**Comment by jkhsjdhjs** [comment] 2024-07-11 22:23
Looks good to me so far! I think you can even move the `activityViewController` out of the if block and make use of it in the else as well.

**Closed** 2024-07-11 23:20 UTC

**Comment by Macleykun** [comment] 2024-07-12 06:58
> Hey @Macleykun I took care of the problem, it now supports iPad this time!

thank you both very much! I just tested it out and it works like arichornlover said!
i really appricate the time and effort this has taken to implement this feature, while it's minor thingie, i think it's great that ytns now fully works regardless of which device!

For DMCA reasons, i do suggest to remove the releases we discussed here, and want to wish you all a great weekend!

**Comment by Macleykun** [comment] 2024-07-12 07:24
Also, i have something to share back to you two if it's any use.
I've found a github action that can automatically get the decrypted ipa that's needed to compile:
https://github.com/YTLitePlus/YTLitePlus/compare/main...Macleykun:YTLitePlus:auto-fetch-ipa

Out of fear of this being noticed by the website that provides said ipa's, i rather want to keep this as private as possible.
Will delete this message right away, as github sends an email.
